import type { Document, DocumentStats } from "../types/documents"

export const mockDocuments: Document[] = [
  {
    id: "1",
    name: "개발환경_설정_가이드.md",
    originalName: "개발환경_설정_가이드.md",
    type: "markdown",
    categoryId: "1",
    categoryName: "개발",
    size: 2411520, // 2.3MB in bytes
    sizeFormatted: "2.3 MB",
    status: "processed",
    uploadedBy: "김개발",
    uploadedById: "user1",
    filePath: "/uploads/documents/dev-setup-guide.md",
    downloadUrl: "/api/documents/1/download",
    extractedText: "개발 환경 설정 가이드입니다...",
    metadata: {
      wordCount: 1250,
      language: "ko",
      encoding: "UTF-8",
    },
    tags: ["개발환경", "설정", "가이드"],
    isPublic: true,
    downloadCount: 45,
    createdAt: "2025-01-09T00:00:00Z",
    updatedAt: "2025-01-09T00:05:00Z",
  },
  {
    id: "2",
    name: "인사규정.pdf",
    originalName: "인사규정_2025.pdf",
    type: "pdf",
    categoryId: "2",
    categoryName: "인사",
    size: 1887436, // 1.8MB in bytes
    sizeFormatted: "1.8 MB",
    status: "processed",
    uploadedBy: "이인사",
    uploadedById: "user2",
    filePath: "/uploads/documents/hr-policy.pdf",
    downloadUrl: "/api/documents/2/download",
    extractedText: "인사 규정 및 정책...",
    metadata: {
      pageCount: 25,
      wordCount: 3500,
      language: "ko",
      author: "인사팀",
      title: "인사규정 2025",
    },
    tags: ["인사", "규정", "정책"],
    isPublic: false,
    downloadCount: 23,
    createdAt: "2025-01-08T00:00:00Z",
    updatedAt: "2025-01-08T00:10:00Z",
  },
  {
    id: "3",
    name: "코드리뷰_프로세스.txt",
    originalName: "코드리뷰_프로세스_가이드.txt",
    type: "text",
    categoryId: "3",
    categoryName: "프로세스",
    size: 524288, // 0.5MB in bytes
    sizeFormatted: "0.5 MB",
    status: "processing",
    uploadedBy: "박개발",
    uploadedById: "user3",
    filePath: "/uploads/documents/code-review-process.txt",
    extractedText: "코드 리뷰 프로세스...",
    metadata: {
      wordCount: 800,
      language: "ko",
      encoding: "UTF-8",
    },
    tags: ["코드리뷰", "프로세스"],
    isPublic: true,
    downloadCount: 12,
    createdAt: "2025-01-07T00:00:00Z",
    updatedAt: "2025-01-07T00:02:00Z",
  },
  {
    id: "4",
    name: "보안정책.docx",
    originalName: "회사_보안정책_v2.docx",
    type: "docx",
    categoryId: "4",
    categoryName: "보안",
    size: 1048576, // 1MB in bytes
    sizeFormatted: "1.0 MB",
    status: "error",
    uploadedBy: "최보안",
    uploadedById: "user4",
    filePath: "/uploads/documents/security-policy.docx",
    metadata: {
      pageCount: 15,
      wordCount: 2200,
      language: "ko",
      author: "보안팀",
    },
    tags: ["보안", "정책"],
    isPublic: false,
    downloadCount: 0,
    createdAt: "2025-01-06T00:00:00Z",
    updatedAt: "2025-01-06T00:15:00Z",
  },
]

export const mockDocumentStats: DocumentStats = {
  totalDocuments: 89,
  processedDocuments: 76,
  processingDocuments: 8,
  errorDocuments: 5,
  totalSize: 157286400, // ~150MB in bytes
  totalSizeFormatted: "150 MB",
}
