/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Chatbot Admin API
 * NestJS chatbot admin application with Slack integration and web crawling
 * OpenAPI spec version: 1.0
 */

export interface AdvancedCrawlRequest {
  /** Website URL to crawl with embeddings */
  url: string;
  /**
   * Maximum number of pages to crawl
   * @minimum 1
   * @maximum 50
   */
  maxPages?: number;
}
