/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Chatbot Admin API
 * NestJS chatbot admin application with Slack integration and web crawling
 * OpenAPI spec version: 1.0
 */

export interface AdvancedCrawlResult {
  /** Crawled URL */
  url: string;
  /** Page title */
  title: string;
  /** Extracted content */
  content: string;
  /** Found links */
  links: string[];
  /** Crawl timestamp */
  timestamp: string;
  /** Text chunks created */
  chunks?: string[];
  /** Embedding vector dimensions */
  embeddingDimensions?: number;
  /** Total number of chunks created */
  totalChunks?: number;
  /** Total execution time in milliseconds */
  executionTime?: number;
}
