/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Chatbot Admin API
 * NestJS chatbot admin application with Slack integration and web crawling
 * OpenAPI spec version: 1.0
 */
import type { BotMessagesResponseMessagesItem } from './botMessagesResponseMessagesItem';
import type { BotMessagesResponseStats } from './botMessagesResponseStats';

export interface BotMessagesResponse {
  /** Array of bot messages */
  messages: BotMessagesResponseMessagesItem[];
  /** Message statistics */
  stats: BotMessagesResponseStats;
  /** Operation success status */
  success: boolean;
  /** Response timestamp */
  timestamp: string;
}
