/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Chatbot Admin API
 * NestJS chatbot admin application with Slack integration and web crawling
 * OpenAPI spec version: 1.0
 */

export type CrawlingControllerGetCrawledThreads200HistoryItem = {
  /** Root message content */
  content?: string;
  /** link URL */
  link?: string;
  /** Creation timestamp */
  createdAt?: string;
  /** Number of messages in thread group */
  count?: number;
};
