/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Chatbot Admin API
 * NestJS chatbot admin application with Slack integration and web crawling
 * OpenAPI spec version: 1.0
 */

export interface CrawlRequest {
  /** URL to crawl */
  url: string;
  /**
   * Crawling depth
   * @minimum 1
   */
  depth?: number;
  /** CSS selector to extract specific content */
  selector?: string;
}
