/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Chatbot Admin API
 * NestJS chatbot admin application with Slack integration and web crawling
 * OpenAPI spec version: 1.0
 */
import type { CrawlingControllerGetCrawledThreads200HistoryItem } from './crawlingControllerGetCrawledThreads200HistoryItem';

export type CrawlingControllerGetCrawledThreads200 = {
  history?: CrawlingControllerGetCrawledThreads200HistoryItem[];
  /** Total number of thread groups */
  total?: number;
};
