/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Chatbot Admin API
 * NestJS chatbot admin application with Slack integration and web crawling
 * OpenAPI spec version: 1.0
 */

export * from './advancedCrawlRequest';
export * from './advancedCrawlResult';
export * from './botMessagesResponse';
export * from './botMessagesResponseMessagesItem';
export * from './botMessagesResponseStats';
export * from './crawlRequest';
export * from './crawlResult';
export * from './deleteMessageRequest';
export * from './messageActionResponse';
export * from './searchRequest';
export * from './sendMessageRequest';
export * from './slackControllerGetBotMessagesParams';
export * from './slackControllerGetBotStatsParams';
export * from './updateMessageRequest';