/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Chatbot Admin API
 * NestJS chatbot admin application with Slack integration and web crawling
 * OpenAPI spec version: 1.0
 */

export interface SearchRequest {
  /** Search query for similarity search */
  query: string;
  /**
   * Maximum number of results to return
   * @minimum 1
   * @maximum 50
   */
  limit?: number;
}
