/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Chatbot Admin API
 * NestJS chatbot admin application with Slack integration and web crawling
 * OpenAPI spec version: 1.0
 */

export type SlackControllerGetBotMessagesParams = {
/**
 * Slack channel ID
 */
channelId?: string;
/**
 * Include thread messages (default: true)
 */
includeThreads?: string;
/**
 * Page number (default: 1)
 */
page?: string;
/**
 * Messages per page (default: 20, max: 100)
 */
limit?: string;
};
