/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Chatbot Admin API
 * NestJS chatbot admin application with Slack integration and web crawling
 * OpenAPI spec version: 1.0
 */

export type SlackControllerGetBotMessagesParams = {
/**
 * Slack channel ID
 */
channelId?: string;
/**
 * Number of messages to retrieve
 */
limit?: string;
/**
 * Oldest message timestamp
 */
oldest?: string;
/**
 * Latest message timestamp
 */
latest?: string;
};
