/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Chatbot Admin API
 * NestJS chatbot admin application with Slack integration and web crawling
 * OpenAPI spec version: 1.0
 */
import type { ThreadCategoryStatsDtoCategory } from './threadCategoryStatsDtoCategory';

export interface ThreadCategoryStatsDto {
  category: ThreadCategoryStatsDtoCategory;
  /** 해당 카테고리의 스레드 개수 */
  count: number;
  /** 전체 대비 비율 (%) */
  percentage: number;
}
