/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Chatbot Admin API
 * NestJS chatbot admin application with Slack integration and web crawling
 * OpenAPI spec version: 1.0
 */
import type { ThreadCategoryStatsDto } from './threadCategoryStatsDto';
import type { ThreadDto } from './threadDto';
import type { ThreadSummaryDtoTopTagsItem } from './threadSummaryDtoTopTagsItem';

export interface ThreadSummaryDto {
  /** 전체 스레드 개수 */
  totalThreads: number;
  /** 카테고리별 통계 */
  categoryStats: ThreadCategoryStatsDto[];
  /** 최근 스레드 목록 */
  recentThreads: ThreadDto[];
  /** 인기 태그 목록 */
  topTags?: ThreadSummaryDtoTopTagsItem[];
}
