/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Chatbot Admin API
 * NestJS chatbot admin application with Slack integration and web crawling
 * OpenAPI spec version: 1.0
 */
import type { ThreadControllerGetThreadsCategory } from './threadControllerGetThreadsCategory';

export type ThreadControllerGetThreadsParams = {
category?: ThreadControllerGetThreadsCategory;
/**
 * 페이지 번호 (1부터 시작)
 * @minimum 1
 */
page?: number;
/**
 * 페이지당 항목 수
 * @minimum 1
 * @maximum 100
 */
limit?: number;
/**
 * 검색 키워드
 */
search?: string;
/**
 * 시작 날짜 (YYYY-MM-DD)
 */
startDate?: string;
/**
 * 종료 날짜 (YYYY-MM-DD)
 */
endDate?: string;
/**
 * 해결된 스레드만 조회
 */
resolvedOnly?: boolean;
};
