/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Chatbot Admin API
 * NestJS chatbot admin application with Slack integration and web crawling
 * OpenAPI spec version: 1.0
 */

export type ThreadCategoryStatsDtoCategory = typeof ThreadCategoryStatsDtoCategory[keyof typeof ThreadCategoryStatsDtoCategory];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ThreadCategoryStatsDtoCategory = {
  technical: 'technical',
  question: 'question',
  discussion: 'discussion',
  announcement: 'announcement',
  other: 'other',
} as const;
