/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Chatbot Admin API
 * NestJS chatbot admin application with Slack integration and web crawling
 * OpenAPI spec version: 1.0
 */

/**
 * 우선순위
 */
export type ThreadDtoPriority = typeof ThreadDtoPriority[keyof typeof ThreadDtoPriority];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ThreadDtoPriority = {
  low: 'low',
  medium: 'medium',
  high: 'high',
} as const;
