/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Chatbot Admin API
 * NestJS chatbot admin application with Slack integration and web crawling
 * OpenAPI spec version: 1.0
 */
import type { ThreadDto } from './threadDto';

export interface ThreadListResponseDto {
  /** 스레드 목록 */
  threads: ThreadDto[];
  /** 전체 스레드 개수 */
  total: number;
  /** 현재 페이지 */
  page: number;
  /** 페이지당 항목 수 */
  limit: number;
  /** 전체 페이지 수 */
  totalPages: number;
}
