/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Chatbot Admin API
 * NestJS chatbot admin application with Slack integration and web crawling
 * OpenAPI spec version: 1.0
 */

export type ThreadControllerGetOverviewStats200CategoryCounts = {
  technical?: number;
  question?: number;
  discussion?: number;
  announcement?: number;
  other?: number;
};
