/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Chatbot Admin API
 * NestJS chatbot admin application with Slack integration and web crawling
 * OpenAPI spec version: 1.0
 */
import type { ThreadControllerGetOverviewStats200CategoryCounts } from './threadControllerGetOverviewStats200CategoryCounts';

export type ThreadControllerGetOverviewStats200 = {
  /** 전체 스레드 수 */
  totalThreads?: number;
  /** 해결된 스레드 수 */
  resolvedThreads?: number;
  /** 미해결 스레드 수 */
  unresolvedThreads?: number;
  categoryCounts?: ThreadControllerGetOverviewStats200CategoryCounts;
};
