/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Chatbot Admin API
 * NestJS chatbot admin application with Slack integration and web crawling
 * OpenAPI spec version: 1.0
 */
import type { ThreadDtoCategory } from './threadDtoCategory';
import type { ThreadDtoPriority } from './threadDtoPriority';

export interface ThreadDto {
  /** 스레드 ID */
  id: string;
  /** 스레드 제목 */
  title: string;
  /** 스레드 내용 */
  content: string;
  category: ThreadDtoCategory;
  /** 생성일시 */
  createdAt: string;
  /** 수정일시 */
  updatedAt: string;
  /** 작성자 ID */
  authorId: string;
  /** 작성자 이름 */
  authorName: string;
  /** 태그 목록 */
  tags?: string[];
  /** 해결 여부 */
  isResolved?: boolean;
  /** 우선순위 */
  priority?: ThreadDtoPriority;
}
