/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Chatbot Admin API
 * NestJS chatbot admin application with Slack integration and web crawling
 * OpenAPI spec version: 1.0
 */

export interface UniversalCrawlRequest {
  /** URL to process (website, PDF, Markdown, or GitHub repository) */
  url: string;
  /**
   * Maximum number of pages to crawl (for websites only)
   * @minimum 1
   * @maximum 150
   */
  maxPages?: number;
}
